apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: IfNotPresent
    args: ["--dockerfile=/workspace/Dockerfile",
            "--context=dir:///workspace",
            "--destination=registry.cn-hangzhou.aliyuncs.com/shuqi66/batch-server:0.0.1"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /workspace
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: aliyun
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim

