apiVersion: batch/v1
kind: Job
metadata:
  name: gateway-admin
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: gateway-admin
        image: gcr.io/kaniko-project/executor:latest
        imagePullPolicy: IfNotPresent
        args: ["--dockerfile=/workspace/Dockerfile",
               "--context=dir:///workspace",
               "--destination=registry.cn-hangzhou.aliyuncs.com/shuqi66/gateway-admin:1.1.10"]
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-storage
            mountPath: /workspace
            subPath: gateway-admin-1.1.10
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: aliyun
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-storage
          persistentVolumeClaim:
            claimName: dockerfile-claim

