apiVersion: batch/v1
kind: Job
metadata:
  name: metrics-server
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: metrics-server
        image: gcr.io/kaniko-project/executor:latest
        imagePullPolicy: IfNotPresent
        args: ["--dockerfile=/workspace/Dockerfile",
               "--context=dir:///workspace",
               "--destination=registry.cn-hangzhou.aliyuncs.com/shuqi66/metrics-server:1.1.3"]
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-storage
            mountPath: /workspace
            subPath: metrics-server-1.1.3
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: aliyun
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-storage
          persistentVolumeClaim:
            claimName: dockerfile-claim

